package model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 11 15:12:01 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgFinishProdAdditionImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        AdditionId {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getAdditionId();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setAdditionId((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineNo {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getLineNo();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setLineNo((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        Style {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getStyle();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Season {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getSeason();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Color {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getColor();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        WorkingHourBasic {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getWorkingHourBasic();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setWorkingHourBasic((String)value);
            }
        }
        ,
        ManpowerBasic {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getManpowerBasic();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setManpowerBasic((String)value);
            }
        }
        ,
        WorkingHourOvertime {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getWorkingHourOvertime();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setWorkingHourOvertime((String)value);
            }
        }
        ,
        ManpowerOvertime {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getManpowerOvertime();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setManpowerOvertime((String)value);
            }
        }
        ,
        WorkingHourExtraot1 {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getWorkingHourExtraot1();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setWorkingHourExtraot1((String)value);
            }
        }
        ,
        ManPowerExtraot1 {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getManPowerExtraot1();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setManPowerExtraot1((String)value);
            }
        }
        ,
        WorkingHourExtraot2 {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getWorkingHourExtraot2();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setWorkingHourExtraot2((String)value);
            }
        }
        ,
        ManPowerExtraot2 {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getManPowerExtraot2();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setManPowerExtraot2((String)value);
            }
        }
        ,
        Buyer {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getBuyer();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setBuyer((String)value);
            }
        }
        ,
        Wah {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getWah();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setWah((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        MnjMfgFinishProdH {
            public Object get(MnjMfgFinishProdAdditionImpl obj) {
                return obj.getMnjMfgFinishProdH();
            }

            public void put(MnjMfgFinishProdAdditionImpl obj, Object value) {
                obj.setMnjMfgFinishProdH((MnjMfgFinishProdHImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgFinishProdAdditionImpl object);

        public abstract void put(MnjMfgFinishProdAdditionImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ADDITIONID = AttributesEnum.AdditionId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int WORKINGHOURBASIC = AttributesEnum.WorkingHourBasic.index();
    public static final int MANPOWERBASIC = AttributesEnum.ManpowerBasic.index();
    public static final int WORKINGHOUROVERTIME = AttributesEnum.WorkingHourOvertime.index();
    public static final int MANPOWEROVERTIME = AttributesEnum.ManpowerOvertime.index();
    public static final int WORKINGHOUREXTRAOT1 = AttributesEnum.WorkingHourExtraot1.index();
    public static final int MANPOWEREXTRAOT1 = AttributesEnum.ManPowerExtraot1.index();
    public static final int WORKINGHOUREXTRAOT2 = AttributesEnum.WorkingHourExtraot2.index();
    public static final int MANPOWEREXTRAOT2 = AttributesEnum.ManPowerExtraot2.index();
    public static final int BUYER = AttributesEnum.Buyer.index();
    public static final int WAH = AttributesEnum.Wah.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int MNJMFGFINISHPRODH = AttributesEnum.MnjMfgFinishProdH.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgFinishProdAdditionImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entities.MnjMfgFinishProdAddition");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for AdditionId, using the alias name AdditionId.
     * @return the AdditionId
     */
    public Number getAdditionId() {
        return (Number)getAttributeInternal(ADDITIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdditionId.
     * @param value value to set the AdditionId
     */
    public void setAdditionId(Number value) {
        setAttributeInternal(ADDITIONID, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LineNo, using the alias name LineNo.
     * @return the LineNo
     */
    public String getLineNo() {
        return (String)getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineNo.
     * @param value value to set the LineNo
     */
    public void setLineNo(String value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for Style, using the alias name Style.
     * @return the Style
     */
    public String getStyle() {
        return (String)getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Style.
     * @param value value to set the Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for Season, using the alias name Season.
     * @return the Season
     */
    public String getSeason() {
        return (String)getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Season.
     * @param value value to set the Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for Color, using the alias name Color.
     * @return the Color
     */
    public String getColor() {
        return (String)getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Color.
     * @param value value to set the Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for WorkingHourBasic, using the alias name WorkingHourBasic.
     * @return the WorkingHourBasic
     */
    public String getWorkingHourBasic() {
        return (String)getAttributeInternal(WORKINGHOURBASIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkingHourBasic.
     * @param value value to set the WorkingHourBasic
     */
    public void setWorkingHourBasic(String value) {
        setAttributeInternal(WORKINGHOURBASIC, value);
    }

    /**
     * Gets the attribute value for ManpowerBasic, using the alias name ManpowerBasic.
     * @return the ManpowerBasic
     */
    public String getManpowerBasic() {
        return (String)getAttributeInternal(MANPOWERBASIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManpowerBasic.
     * @param value value to set the ManpowerBasic
     */
    public void setManpowerBasic(String value) {
        setAttributeInternal(MANPOWERBASIC, value);
    }

    /**
     * Gets the attribute value for WorkingHourOvertime, using the alias name WorkingHourOvertime.
     * @return the WorkingHourOvertime
     */
    public String getWorkingHourOvertime() {
        return (String)getAttributeInternal(WORKINGHOUROVERTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkingHourOvertime.
     * @param value value to set the WorkingHourOvertime
     */
    public void setWorkingHourOvertime(String value) {
        setAttributeInternal(WORKINGHOUROVERTIME, value);
    }

    /**
     * Gets the attribute value for ManpowerOvertime, using the alias name ManpowerOvertime.
     * @return the ManpowerOvertime
     */
    public String getManpowerOvertime() {
        return (String)getAttributeInternal(MANPOWEROVERTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManpowerOvertime.
     * @param value value to set the ManpowerOvertime
     */
    public void setManpowerOvertime(String value) {
        setAttributeInternal(MANPOWEROVERTIME, value);
    }

    /**
     * Gets the attribute value for WorkingHourExtraot1, using the alias name WorkingHourExtraot1.
     * @return the WorkingHourExtraot1
     */
    public String getWorkingHourExtraot1() {
        return (String)getAttributeInternal(WORKINGHOUREXTRAOT1);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkingHourExtraot1.
     * @param value value to set the WorkingHourExtraot1
     */
    public void setWorkingHourExtraot1(String value) {
        setAttributeInternal(WORKINGHOUREXTRAOT1, value);
    }

    /**
     * Gets the attribute value for ManPowerExtraot1, using the alias name ManPowerExtraot1.
     * @return the ManPowerExtraot1
     */
    public String getManPowerExtraot1() {
        return (String)getAttributeInternal(MANPOWEREXTRAOT1);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManPowerExtraot1.
     * @param value value to set the ManPowerExtraot1
     */
    public void setManPowerExtraot1(String value) {
        setAttributeInternal(MANPOWEREXTRAOT1, value);
    }

    /**
     * Gets the attribute value for WorkingHourExtraot2, using the alias name WorkingHourExtraot2.
     * @return the WorkingHourExtraot2
     */
    public String getWorkingHourExtraot2() {
        return (String)getAttributeInternal(WORKINGHOUREXTRAOT2);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkingHourExtraot2.
     * @param value value to set the WorkingHourExtraot2
     */
    public void setWorkingHourExtraot2(String value) {
        setAttributeInternal(WORKINGHOUREXTRAOT2, value);
    }

    /**
     * Gets the attribute value for ManPowerExtraot2, using the alias name ManPowerExtraot2.
     * @return the ManPowerExtraot2
     */
    public String getManPowerExtraot2() {
        return (String)getAttributeInternal(MANPOWEREXTRAOT2);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManPowerExtraot2.
     * @param value value to set the ManPowerExtraot2
     */
    public void setManPowerExtraot2(String value) {
        setAttributeInternal(MANPOWEREXTRAOT2, value);
    }

    /**
     * Gets the attribute value for Buyer, using the alias name Buyer.
     * @return the Buyer
     */
    public String getBuyer() {
        return (String)getAttributeInternal(BUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Buyer.
     * @param value value to set the Buyer
     */
    public void setBuyer(String value) {
        setAttributeInternal(BUYER, value);
    }

    /**
     * Gets the attribute value for Wah, using the alias name Wah.
     * @return the Wah
     */
    public String getWah() {
        return (String)getAttributeInternal(WAH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Wah.
     * @param value value to set the Wah
     */
    public void setWah(String value) {
        setAttributeInternal(WAH, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgFinishProdHImpl.
     */
    public MnjMfgFinishProdHImpl getMnjMfgFinishProdH() {
        return (MnjMfgFinishProdHImpl)getAttributeInternal(MNJMFGFINISHPRODH);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgFinishProdHImpl.
     */
    public void setMnjMfgFinishProdH(MnjMfgFinishProdHImpl value) {
        setAttributeInternal(MNJMFGFINISHPRODH, value);
    }


    /**
     * @param additionId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number additionId) {
        return new Key(new Object[]{additionId});
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_FINISH_PROD_ADDITION_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setAdditionId(sVal);
    }
    
    /**
         * Custom DML update/insert/delete logic here.
         * @param operation the operation type
         * @param e the transaction event
         */
        protected void doDML(int operation, TransactionEvent e) {
            Map sessionScope = ADFContext.getCurrent().getSessionScope();   
            String user = (String)sessionScope.get("userId");
            String orgId  =(String)sessionScope.get("orgId");
            String unitName  =(String)sessionScope.get("unitName");
            
            System.out.println("ASSES INS DO DML 1 ------------------>"+user);
            System.out.println("ASSES INS DO DML 2------------------>"+orgId);
            System.out.println("ASSES INS DML 3 ------------------>"+unitName);
            
            if(DML_UPDATE == operation){
                      try {
                          
                          setLastUpdateDate((Date)Date.getCurrentDate()); 
                          setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                      } catch (SQLException f) {
                          System.out.println(f.getMessage());
                      }
                  }
                  else if (DML_INSERT == operation){
                   
                      try {
                          
                          //setHeaderNo(getSrNoString());
                          //setOrgId(new oracle.jbo.domain.Number(orgId));
                          //setAttribute1(unitName);
                          setCreationDate((Date)Date.getCurrentDate());  
                          setCreatedBy(new oracle.jbo.domain.Number(user));
                         
                         
                         
                      } catch (SQLException f) {
                          ;
                      }
                  } 
            
            super.doDML(operation, e);
        }



}
