package model.entities;

import java.sql.SQLException;

import java.text.DateFormat;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 11 20:10:33 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgFinishProdLImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        LineId {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getLineId();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineNo {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getLineNo();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setLineNo((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        Style {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getStyle();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Season {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getSeason();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        BpoNo {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getBpoNo();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        StnNo {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getStnNo();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setStnNo((String)value);
            }
        }
        ,
        SaleOrderId {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getSaleOrderId();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setSaleOrderId((Number)value);
            }
        }
        ,
        DayRej {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getDayRej();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setDayRej((Number)value);
            }
        }
        ,
        TotalRej {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getTotalRej();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setTotalRej((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        ProdType {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getProdType();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setProdType((String)value);
            }
        }
        ,
        JobId {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getJobId();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setJobId((Number)value);
            }
        }
        ,
        ErrorMessage {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getErrorMessage();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setErrorMessage((String)value);
            }
        }
        ,
        LastAction {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getLastAction();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setLastAction((String)value);
            }
        }
        ,
        DivisionId {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setDivisionId((Number)value);
            }
        }
        ,
        Color {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getColor();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        TotalInput {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getTotalInput();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setTotalInput((Number)value);
            }
        }
        ,
        DayProduction {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getDayProduction();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setDayProduction((Number)value);
            }
        }
        ,
        TotalProduction {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getTotalProduction();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setTotalProduction((Number)value);
            }
        }
        ,
        DayRejection {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getDayRejection();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setDayRejection((Number)value);
            }
        }
        ,
        TotalRejection {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getTotalRejection();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setTotalRejection((Number)value);
            }
        }
        ,
        Wip {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getWip();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setWip((Number)value);
            }
        }
        ,
        ProductyType {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getProductyType();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setProductyType((String)value);
            }
        }
        ,
        PreLineoutput {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getPreLineoutput();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setPreLineoutput((Number)value);
            }
        }
        ,
        BelLineoutout {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getBelLineoutout();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setBelLineoutout((Number)value);
            }
        }
        ,
        PostedStatus {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getPostedStatus();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setPostedStatus((String)value);
            }
        }
        ,
        WorkingHourBasic {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getWorkingHourBasic();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setWorkingHourBasic((String)value);
            }
        }
        ,
        ManpowerBasic {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getManpowerBasic();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setManpowerBasic((String)value);
            }
        }
        ,
        WorkingHourOvertime {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getWorkingHourOvertime();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setWorkingHourOvertime((String)value);
            }
        }
        ,
        ManpowerOvertime {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getManpowerOvertime();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setManpowerOvertime((String)value);
            }
        }
        ,
        WorkingHourExtraot1 {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getWorkingHourExtraot1();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setWorkingHourExtraot1((String)value);
            }
        }
        ,
        ManPowerExtraot1 {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getManPowerExtraot1();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setManPowerExtraot1((String)value);
            }
        }
        ,
        WorkingHourExtraot2 {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getWorkingHourExtraot2();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setWorkingHourExtraot2((String)value);
            }
        }
        ,
        ManPowerExtraot2 {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getManPowerExtraot2();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setManPowerExtraot2((String)value);
            }
        }
        ,
        Sam {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getSam();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setSam((Number)value);
            }
        }
        ,
        ProducedMin {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getProducedMin();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setProducedMin((Number)value);
            }
        }
        ,
        SamValue {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getSamValue();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setSamValue((Number)value);
            }
        }
        ,
        Wash {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getWash();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setWash((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        BpoId {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getBpoId();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setBpoId((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getSystemId();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        MnjMfgFinishProdD {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getMnjMfgFinishProdD();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgFinishProdH {
            public Object get(MnjMfgFinishProdLImpl obj) {
                return obj.getMnjMfgFinishProdH();
            }

            public void put(MnjMfgFinishProdLImpl obj, Object value) {
                obj.setMnjMfgFinishProdH((MnjMfgFinishProdHImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgFinishProdLImpl object);

        public abstract void put(MnjMfgFinishProdLImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


 //   public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();


    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int STNNO = AttributesEnum.StnNo.index();
    public static final int SALEORDERID = AttributesEnum.SaleOrderId.index();
    public static final int DAYREJ = AttributesEnum.DayRej.index();
    public static final int TOTALREJ = AttributesEnum.TotalRej.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int PRODTYPE = AttributesEnum.ProdType.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int ERRORMESSAGE = AttributesEnum.ErrorMessage.index();
    public static final int LASTACTION = AttributesEnum.LastAction.index();
    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int TOTALINPUT = AttributesEnum.TotalInput.index();
    public static final int DAYPRODUCTION = AttributesEnum.DayProduction.index();
    public static final int TOTALPRODUCTION = AttributesEnum.TotalProduction.index();
    public static final int DAYREJECTION = AttributesEnum.DayRejection.index();
    public static final int TOTALREJECTION = AttributesEnum.TotalRejection.index();
    public static final int WIP = AttributesEnum.Wip.index();
    public static final int PRODUCTYTYPE = AttributesEnum.ProductyType.index();
    public static final int PRELINEOUTPUT = AttributesEnum.PreLineoutput.index();
    public static final int BELLINEOUTOUT = AttributesEnum.BelLineoutout.index();
    public static final int POSTEDSTATUS = AttributesEnum.PostedStatus.index();
    public static final int WORKINGHOURBASIC = AttributesEnum.WorkingHourBasic.index();
    public static final int MANPOWERBASIC = AttributesEnum.ManpowerBasic.index();
    public static final int WORKINGHOUROVERTIME = AttributesEnum.WorkingHourOvertime.index();
    public static final int MANPOWEROVERTIME = AttributesEnum.ManpowerOvertime.index();
    public static final int WORKINGHOUREXTRAOT1 = AttributesEnum.WorkingHourExtraot1.index();
    public static final int MANPOWEREXTRAOT1 = AttributesEnum.ManPowerExtraot1.index();
    public static final int WORKINGHOUREXTRAOT2 = AttributesEnum.WorkingHourExtraot2.index();
    public static final int MANPOWEREXTRAOT2 = AttributesEnum.ManPowerExtraot2.index();
    public static final int SAM = AttributesEnum.Sam.index();
    public static final int PRODUCEDMIN = AttributesEnum.ProducedMin.index();
    public static final int SAMVALUE = AttributesEnum.SamValue.index();
    public static final int WASH = AttributesEnum.Wash.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int MNJMFGFINISHPRODD = AttributesEnum.MnjMfgFinishProdD.index();
    public static final int MNJMFGFINISHPRODH = AttributesEnum.MnjMfgFinishProdH.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgFinishProdLImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entities.MnjMfgFinishProdL");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LineNo, using the alias name LineNo.
     * @return the LineNo
     */
    public String getLineNo() {
        return (String)getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineNo.
     * @param value value to set the LineNo
     */
    public void setLineNo(String value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for Style, using the alias name Style.
     * @return the Style
     */
    public String getStyle() {
        return (String)getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Style.
     * @param value value to set the Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for Season, using the alias name Season.
     * @return the Season
     */
    public String getSeason() {
        return (String)getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Season.
     * @param value value to set the Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for BpoNo, using the alias name BpoNo.
     * @return the BpoNo
     */
    public String getBpoNo() {
        return (String)getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoNo.
     * @param value value to set the BpoNo
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for StnNo, using the alias name StnNo.
     * @return the StnNo
     */
    public String getStnNo() {
        return (String)getAttributeInternal(STNNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StnNo.
     * @param value value to set the StnNo
     */
    public void setStnNo(String value) {
        setAttributeInternal(STNNO, value);
    }

    /**
     * Gets the attribute value for SaleOrderId, using the alias name SaleOrderId.
     * @return the SaleOrderId
     */
    public Number getSaleOrderId() {
        return (Number)getAttributeInternal(SALEORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleOrderId.
     * @param value value to set the SaleOrderId
     */
    public void setSaleOrderId(Number value) {
        setAttributeInternal(SALEORDERID, value);
    }

    /**
     * Gets the attribute value for DayRej, using the alias name DayRej.
     * @return the DayRej
     */
    public Number getDayRej() {
        return (Number)getAttributeInternal(DAYREJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for DayRej.
     * @param value value to set the DayRej
     */
    public void setDayRej(Number value) {
        setAttributeInternal(DAYREJ, value);
    }

    /**
     * Gets the attribute value for TotalRej, using the alias name TotalRej.
     * @return the TotalRej
     */
    public Number getTotalRej() {
        return (Number)getAttributeInternal(TOTALREJ);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalRej.
     * @param value value to set the TotalRej
     */
    public void setTotalRej(Number value) {
        setAttributeInternal(TOTALREJ, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for InventoryItemId, using the alias name InventoryItemId.
     * @return the InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number)getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryItemId.
     * @param value value to set the InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for ProdType, using the alias name ProdType.
     * @return the ProdType
     */
    public String getProdType() {
        return (String)getAttributeInternal(PRODTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdType.
     * @param value value to set the ProdType
     */
    public void setProdType(String value) {
        setAttributeInternal(PRODTYPE, value);
    }

    /**
     * Gets the attribute value for JobId, using the alias name JobId.
     * @return the JobId
     */
    public Number getJobId() {
        return (Number)getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobId.
     * @param value value to set the JobId
     */
    public void setJobId(Number value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for ErrorMessage, using the alias name ErrorMessage.
     * @return the ErrorMessage
     */
    public String getErrorMessage() {
        return (String)getAttributeInternal(ERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ErrorMessage.
     * @param value value to set the ErrorMessage
     */
    public void setErrorMessage(String value) {
        setAttributeInternal(ERRORMESSAGE, value);
    }

    /**
     * Gets the attribute value for LastAction, using the alias name LastAction.
     * @return the LastAction
     */
    public String getLastAction() {
        return (String)getAttributeInternal(LASTACTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastAction.
     * @param value value to set the LastAction
     */
    public void setLastAction(String value) {
        setAttributeInternal(LASTACTION, value);
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public Number getDivisionId() {
        return (Number)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(Number value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for Color, using the alias name Color.
     * @return the Color
     */
    public String getColor() {
        return (String)getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Color.
     * @param value value to set the Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for TotalInput, using the alias name TotalInput.
     * @return the TotalInput
     */
    public Number getTotalInput() {
        return (Number)getAttributeInternal(TOTALINPUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalInput.
     * @param value value to set the TotalInput
     */
    public void setTotalInput(Number value) {
        setAttributeInternal(TOTALINPUT, value);
    }

    /**
     * Gets the attribute value for DayProduction, using the alias name DayProduction.
     * @return the DayProduction
     */
    public Number getDayProduction() {
        return (Number)getAttributeInternal(DAYPRODUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for DayProduction.
     * @param value value to set the DayProduction
     */
    public void setDayProduction(Number value) {
        setAttributeInternal(DAYPRODUCTION, value);
    }

    /**
     * Gets the attribute value for TotalProduction, using the alias name TotalProduction.
     * @return the TotalProduction
     */
    public Number getTotalProduction() {
        return (Number)getAttributeInternal(TOTALPRODUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalProduction.
     * @param value value to set the TotalProduction
     */
    public void setTotalProduction(Number value) {
        setAttributeInternal(TOTALPRODUCTION, value);
    }

    /**
     * Gets the attribute value for DayRejection, using the alias name DayRejection.
     * @return the DayRejection
     */
    public Number getDayRejection() {
        return (Number)getAttributeInternal(DAYREJECTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for DayRejection.
     * @param value value to set the DayRejection
     */
    public void setDayRejection(Number value) {
        setAttributeInternal(DAYREJECTION, value);
    }

    /**
     * Gets the attribute value for TotalRejection, using the alias name TotalRejection.
     * @return the TotalRejection
     */
    public Number getTotalRejection() {
        return (Number)getAttributeInternal(TOTALREJECTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalRejection.
     * @param value value to set the TotalRejection
     */
    public void setTotalRejection(Number value) {
        setAttributeInternal(TOTALREJECTION, value);
    }

    /**
     * Gets the attribute value for Wip, using the alias name Wip.
     * @return the Wip
     */
    public Number getWip() {
        return (Number)getAttributeInternal(WIP);
    }

    /**
     * Sets <code>value</code> as the attribute value for Wip.
     * @param value value to set the Wip
     */
    public void setWip(Number value) {
        setAttributeInternal(WIP, value);
    }

    /**
     * Gets the attribute value for ProductyType, using the alias name ProductyType.
     * @return the ProductyType
     */
    public String getProductyType() {
        return (String)getAttributeInternal(PRODUCTYTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductyType.
     * @param value value to set the ProductyType
     */
    public void setProductyType(String value) {
        setAttributeInternal(PRODUCTYTYPE, value);
    }

    /**
     * Gets the attribute value for PreLineoutput, using the alias name PreLineoutput.
     * @return the PreLineoutput
     */
    public Number getPreLineoutput() {
        return (Number)getAttributeInternal(PRELINEOUTPUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreLineoutput.
     * @param value value to set the PreLineoutput
     */
    public void setPreLineoutput(Number value) {
        setAttributeInternal(PRELINEOUTPUT, value);
    }

    /**
     * Gets the attribute value for BelLineoutout, using the alias name BelLineoutout.
     * @return the BelLineoutout
     */
    public Number getBelLineoutout() {
        return (Number)getAttributeInternal(BELLINEOUTOUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for BelLineoutout.
     * @param value value to set the BelLineoutout
     */
    public void setBelLineoutout(Number value) {
        setAttributeInternal(BELLINEOUTOUT, value);
    }

    /**
     * Gets the attribute value for PostedStatus, using the alias name PostedStatus.
     * @return the PostedStatus
     */
    public String getPostedStatus() {
        return (String)getAttributeInternal(POSTEDSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostedStatus.
     * @param value value to set the PostedStatus
     */
    public void setPostedStatus(String value) {
        setAttributeInternal(POSTEDSTATUS, value);
    }

    /**
     * Gets the attribute value for WorkingHourBasic, using the alias name WorkingHourBasic.
     * @return the WorkingHourBasic
     */
    public String getWorkingHourBasic() {
        return (String)getAttributeInternal(WORKINGHOURBASIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkingHourBasic.
     * @param value value to set the WorkingHourBasic
     */
    public void setWorkingHourBasic(String value) {
        setAttributeInternal(WORKINGHOURBASIC, value);
    }

    /**
     * Gets the attribute value for ManpowerBasic, using the alias name ManpowerBasic.
     * @return the ManpowerBasic
     */
    public String getManpowerBasic() {
        return (String)getAttributeInternal(MANPOWERBASIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManpowerBasic.
     * @param value value to set the ManpowerBasic
     */
    public void setManpowerBasic(String value) {
        setAttributeInternal(MANPOWERBASIC, value);
    }

    /**
     * Gets the attribute value for WorkingHourOvertime, using the alias name WorkingHourOvertime.
     * @return the WorkingHourOvertime
     */
    public String getWorkingHourOvertime() {
        return (String)getAttributeInternal(WORKINGHOUROVERTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkingHourOvertime.
     * @param value value to set the WorkingHourOvertime
     */
    public void setWorkingHourOvertime(String value) {
        setAttributeInternal(WORKINGHOUROVERTIME, value);
    }

    /**
     * Gets the attribute value for ManpowerOvertime, using the alias name ManpowerOvertime.
     * @return the ManpowerOvertime
     */
    public String getManpowerOvertime() {
        return (String)getAttributeInternal(MANPOWEROVERTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManpowerOvertime.
     * @param value value to set the ManpowerOvertime
     */
    public void setManpowerOvertime(String value) {
        setAttributeInternal(MANPOWEROVERTIME, value);
    }

    /**
     * Gets the attribute value for WorkingHourExtraot1, using the alias name WorkingHourExtraot1.
     * @return the WorkingHourExtraot1
     */
    public String getWorkingHourExtraot1() {
        return (String)getAttributeInternal(WORKINGHOUREXTRAOT1);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkingHourExtraot1.
     * @param value value to set the WorkingHourExtraot1
     */
    public void setWorkingHourExtraot1(String value) {
        setAttributeInternal(WORKINGHOUREXTRAOT1, value);
    }

    /**
     * Gets the attribute value for ManPowerExtraot1, using the alias name ManPowerExtraot1.
     * @return the ManPowerExtraot1
     */
    public String getManPowerExtraot1() {
        return (String)getAttributeInternal(MANPOWEREXTRAOT1);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManPowerExtraot1.
     * @param value value to set the ManPowerExtraot1
     */
    public void setManPowerExtraot1(String value) {
        setAttributeInternal(MANPOWEREXTRAOT1, value);
    }

    /**
     * Gets the attribute value for WorkingHourExtraot2, using the alias name WorkingHourExtraot2.
     * @return the WorkingHourExtraot2
     */
    public String getWorkingHourExtraot2() {
        return (String)getAttributeInternal(WORKINGHOUREXTRAOT2);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkingHourExtraot2.
     * @param value value to set the WorkingHourExtraot2
     */
    public void setWorkingHourExtraot2(String value) {
        setAttributeInternal(WORKINGHOUREXTRAOT2, value);
    }

    /**
     * Gets the attribute value for ManPowerExtraot2, using the alias name ManPowerExtraot2.
     * @return the ManPowerExtraot2
     */
    public String getManPowerExtraot2() {
        return (String)getAttributeInternal(MANPOWEREXTRAOT2);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManPowerExtraot2.
     * @param value value to set the ManPowerExtraot2
     */
    public void setManPowerExtraot2(String value) {
        setAttributeInternal(MANPOWEREXTRAOT2, value);
    }

    /**
     * Gets the attribute value for Sam, using the alias name Sam.
     * @return the Sam
     */
    public Number getSam() {
        return (Number)getAttributeInternal(SAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sam.
     * @param value value to set the Sam
     */
    public void setSam(Number value) {
        setAttributeInternal(SAM, value);
    }

    /**
     * Gets the attribute value for ProducedMin, using the alias name ProducedMin.
     * @return the ProducedMin
     */
    public Number getProducedMin() {
        return (Number)getAttributeInternal(PRODUCEDMIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProducedMin.
     * @param value value to set the ProducedMin
     */
    public void setProducedMin(Number value) {
        setAttributeInternal(PRODUCEDMIN, value);
    }

    /**
     * Gets the attribute value for SamValue, using the alias name SamValue.
     * @return the SamValue
     */
    public Number getSamValue() {
        return (Number)getAttributeInternal(SAMVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SamValue.
     * @param value value to set the SamValue
     */
    public void setSamValue(Number value) {
        setAttributeInternal(SAMVALUE, value);
    }

    /**
     * Gets the attribute value for Wash, using the alias name Wash.
     * @return the Wash
     */
    public String getWash() {
        return (String)getAttributeInternal(WASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Wash.
     * @param value value to set the Wash
     */
    public void setWash(String value) {
        setAttributeInternal(WASH, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgFinishProdD() {
        return (RowIterator)getAttributeInternal(MNJMFGFINISHPRODD);
    }

    /**
     * @return the associated entity MnjMfgFinishProdHImpl.
     */
    public MnjMfgFinishProdHImpl getMnjMfgFinishProdH() {
        return (MnjMfgFinishProdHImpl)getAttributeInternal(MNJMFGFINISHPRODH);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgFinishProdHImpl.
     */
    public void setMnjMfgFinishProdH(MnjMfgFinishProdHImpl value) {
        setAttributeInternal(MNJMFGFINISHPRODH, value);
    }


    /**
     * @param lineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number lineId) {
        return new Key(new Object[]{lineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_FINISH_PROD_L_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setLineId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();   
        String user = (String)sessionScope.get("userId");
        String orgId  =(String)sessionScope.get("orgId");
        String unitName  =(String)sessionScope.get("unitName");
        
        System.out.println("ASSES INS DO DML 1 ------------------>"+user);
        System.out.println("ASSES INS DO DML 2------------------>"+orgId);
        System.out.println("ASSES INS DML 3 ------------------>"+unitName);
        
        if(DML_UPDATE == operation){
                  try {
                      
                      setLastUpdateDate((Date)Date.getCurrentDate()); 
                      setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                  } catch (SQLException f) {
                      System.out.println(f.getMessage());
                  }
              }
              else if (DML_INSERT == operation){
               
                  try {
                      
                      //setHeaderNo(getSrNoString());
                      //setOrgId(new oracle.jbo.domain.Number(orgId));
                      //setAttribute1(unitName);
                      setCreationDate((Date)Date.getCurrentDate());  
                      setCreatedBy(new oracle.jbo.domain.Number(user));
                     
                     
                     
                  } catch (SQLException f) {
                      ;
                  }
              } 
        
        super.doDML(operation, e);
        
    }
    
    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
//    public void setLastUpdatedDate(Date value) {
//        setAttributeInternal(LASTUPDATEDDATE, value);
//    }
    
    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
//    public Date getLastUpdatedDate() {
//        return (Date)getAttributeInternal(LASTUPDATEDDATE);
//    }
    
    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for BpoId, using the alias name BpoId.
     * @return the BpoId
     */
    public Number getBpoId() {
        return (Number)getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoId.
     * @param value value to set the BpoId
     */
    public void setBpoId(Number value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * Gets the attribute value for SystemId, using the alias name SystemId.
     * @return the SystemId
     */
    public Number getSystemId() {
        return (Number)getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SystemId.
     * @param value value to set the SystemId
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     *Converts a String to oracle.jbo.domain.Date
     * @param String
     * @return oracle.jbo.domain.Date
     */
    public oracle.jbo.domain.Date castToJBODate(String aDate) throws ParseException {
              DateFormat formatter;
              java.util.Date date; 
     
              if(aDate!=null){
     
                try {
     
                  formatter = new SimpleDateFormat("dd/MMM/yyyy");
                  date = formatter.parse(aDate);
                  java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                  oracle.jbo.domain.Date jboDate = new oracle.jbo.domain.Date(sqlDate);
     
                    return jboDate;
                   } catch (ParseException e) {
     
                            e.printStackTrace();
                    }
     
             }
     
             return null;
    }
   
    
    

    


}
