package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 11 15:27:57 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdditionPOPVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AdditionPOPVOImpl() {
    }
}
