package model.lov;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 11 15:27:56 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdditionPOPVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineNo {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getLineNo();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setLineNo((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        Style {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getStyle();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Season {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        BuyerName {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getBuyerName();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setBuyerName((String)value);
            }
        }
        ,
        Color {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getColor();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        CurrentStyle {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getCurrentStyle();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setCurrentStyle((String)value);
            }
        }
        ,
        CurrentSeason {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getCurrentSeason();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setCurrentSeason((String)value);
            }
        }
        ,
        Wash {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getWash();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setWash((String)value);
            }
        }
        ,
        FlagNEW {
            public Object get(AdditionPOPVORowImpl obj) {
                return obj.getFlagNEW();
            }

            public void put(AdditionPOPVORowImpl obj, Object value) {
                obj.setFlagNEW((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(AdditionPOPVORowImpl object);

        public abstract void put(AdditionPOPVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int CURRENTSTYLE = AttributesEnum.CurrentStyle.index();
    public static final int CURRENTSEASON = AttributesEnum.CurrentSeason.index();
    public static final int WASH = AttributesEnum.Wash.index();
    public static final int FLAGNEW = AttributesEnum.FlagNEW.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AdditionPOPVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HeaderId.
     * @param value value to set the  HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LineNo.
     * @return the LineNo
     */
    public String getLineNo() {
        return (String) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LineNo.
     * @param value value to set the  LineNo
     */
    public void setLineNo(String value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerId.
     * @param value value to set the  BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Style.
     * @return the Style
     */
    public String getStyle() {
        return (String) getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Style.
     * @param value value to set the  Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerName.
     * @return the BuyerName
     */
    public String getBuyerName() {
        return (String) getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerName.
     * @param value value to set the  BuyerName
     */
    public void setBuyerName(String value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Color.
     * @return the Color
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Color.
     * @param value value to set the  Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyle.
     * @return the CurrentStyle
     */
    public String getCurrentStyle() {
        return (String) getAttributeInternal(CURRENTSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyle.
     * @param value value to set the  CurrentStyle
     */
    public void setCurrentStyle(String value) {
        setAttributeInternal(CURRENTSTYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentSeason.
     * @return the CurrentSeason
     */
    public String getCurrentSeason() {
        return (String) getAttributeInternal(CURRENTSEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentSeason.
     * @param value value to set the  CurrentSeason
     */
    public void setCurrentSeason(String value) {
        setAttributeInternal(CURRENTSEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Wash.
     * @return the Wash
     */
    public String getWash() {
        return (String) getAttributeInternal(WASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Wash.
     * @param value value to set the  Wash
     */
    public void setWash(String value) {
        setAttributeInternal(WASH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FlagNEW.
     * @return the FlagNEW
     */
    public String getFlagNEW() {
        return (String) getAttributeInternal(FLAGNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FlagNEW.
     * @param value value to set the  FlagNEW
     */
    public void setFlagNEW(String value) {
        setAttributeInternal(FLAGNEW, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
