package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 13 13:55:19 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FinishingLineLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FinishingLineLOVImpl() {
    }
}
