package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 12 12:29:05 PKT 2016
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void FillLines();

    void FillDetails();

    String callPost(String headerId);

    String completion(String headerId);

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);

    int sumtotalProduction();

    int sumtotalRejection();

    int sumtotalRejectiondetail();

    int sumtotalprodetail();

    String CalculateTotalProductionNewLINE(String headerId);

    void setRollwhereClause1();

    void FillLinesNEW();

    void setSizeWherCaluseNew();

    void FillLinesNEWTab();

    void selectAllLines(String FlagNEWTab);

    void popupDeselectActionListener();
}
